### ISSUE TITLE
Dave and Bambi 3.0 source code is out now please update your code

### ISSUE THREAD

**Issue by matthewfro1717** [Magman03k7/VsDave-main-Shaggy-ExtraKeys#1]
Here it is https://github.com/MoldyGH/VsDave and it is no longer private

**Comment by Magman03k7** [comment]
> Here it is https://github.com/MoldyGH/VsDave and it is no longer private

I'm already on it, but thanks for telling me!

**Comment by matthewfro1717** [comment]
no problem

**Comment by funniperson1122** [comment]
its private :[

**Comment by matthewfro1717** [comment]
I have been waiting a long time for you to update this repository  I know you have the 3.0 extra keys addon on gamebanana now please update your code
